#!/usr/bin/env python3
from pathlib import Path
import re,sys
if len(sys.argv)!=2: raise SystemExit('usage: apply.py <source-root>')
root=Path(sys.argv[1]).resolve()
def read(r):return (root/r).read_text(encoding='utf-8')
def write(r,t):p=root/r;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(t,encoding='utf-8')
def rep(r,a,b,l,all=False):
 t=read(r)
 if a not in t:raise SystemExit(f'{l}: marker not found in {r}')
 write(r,t.replace(a,b) if all else t.replace(a,b,1))

bp='internal/installer/builtin.go';b=read(bp)
if 'func Fail2banManifest()' not in b:
 m=r'''

func Fail2banManifest() Manifest {
 return Manifest{
  SchemaVersion:ManifestSchemaVersion,ID:"fail2ban",Name:"Fail2ban SSH Protection",
  SupportedOS:[]OSConstraint{{ID:"ubuntu",Version:"24.04"}},
  Versions:[]VersionSpec{{Version:"ubuntu-24.04",Default:true}},
  Resources:ResourceRequirements{MinMemoryBytes:128*1024*1024,MinDiskBytes:256*1024*1024},
  Preflight:[]CheckSpec{{ID:"sshd-present",Kind:"fail2ban_sshd",Params:map[string]string{"service":"ssh.service"}},{ID:"fail2ban-absent",Kind:"package_absent",Params:map[string]string{"name":"fail2ban"}}},
  InstallSteps:[]OperationSpec{{ID:"install-fail2ban",Action:"apt.package.install",Params:map[string]string{"set":"fail2ban-ssh"}},{ID:"write-sshd-jail",Action:"file.template",Params:map[string]string{"managed":"hyzorax-sshd-jail"}},{ID:"enable-fail2ban",Action:"service.enable",Params:map[string]string{"name":"fail2ban"}},{ID:"start-fail2ban",Action:"service.start",Params:map[string]string{"name":"fail2ban"}}},
  HealthChecks:[]CheckSpec{{ID:"fail2ban-service",Kind:"service_active",Params:map[string]string{"name":"fail2ban"}},{ID:"sshd-jail",Kind:"fail2ban_sshd_jail",Params:map[string]string{"maxretry":"5","findtime":"600","bantime":"3600"}}},
  UninstallSteps:[]OperationSpec{{ID:"stop-fail2ban",Action:"service.stop",Params:map[string]string{"name":"fail2ban"}},{ID:"remove-fail2ban",Action:"apt.package.remove",Params:map[string]string{"set":"fail2ban-ssh"}}},
  RollbackPolicy:"required",RollbackSteps:[]OperationSpec{{ID:"rollback-stop-fail2ban",Action:"service.stop",Params:map[string]string{"name":"fail2ban"}},{ID:"rollback-remove-fail2ban",Action:"apt.package.remove",Params:map[string]string{"set":"fail2ban-ssh"}}},
 }
}
'''
 marker='func BuiltinCatalog() (*Catalog, error) {'
 if marker not in b:raise SystemExit('BuiltinCatalog marker not found')
 b=b.replace(marker,m+'\n'+marker,1);x=re.search(r'return NewCatalog\(\[\]Manifest\{([^}]*)\}\)',b)
 if not x:raise SystemExit('catalog list not found')
 vals=x.group(1).strip();vals+=("," if vals and not vals.endswith(',') else '')
 b=b[:x.start()]+'return NewCatalog([]Manifest{'+vals+' Fail2banManifest()})'+b[x.end():];write(bp,b)
mp='internal/installer/manifest.go';t=read(mp);x=re.search(r'var allowedCheckKinds = map\[string\]struct\{\}\{\n(?P<body>.*?)\n\}',t,re.DOTALL)
if not x:raise SystemExit('allowedCheckKinds not found')
e=set(re.findall(r'"([a-z0-9_]+)"\s*:',x.group('body')));e.update({'fail2ban_sshd','fail2ban_sshd_jail'});body='\n'.join(f'\t"{n}": {{}},' for n in sorted(e));write(mp,t[:x.start()]+'var allowedCheckKinds = map[string]struct{}{\n'+body+'\n}'+t[x.end():])
write('internal/installer/fail2ban_test.go',r'''package installer
import "testing"
func TestFail2banManifestIsValidAndSSHFirst(t *testing.T){m:=Fail2banManifest();if err:=ValidateManifest(m);err!=nil{t.Fatal(err)};if len(m.Ports)!=0{t.Fatalf("Fail2ban should not claim a listening port: %#v",m.Ports)};if m.RollbackPolicy!="required"{t.Fatal("rollback must be required")};c,err:=BuiltinCatalog();if err!=nil{t.Fatal(err)};p,err:=c.BuildPlan([]string{"fail2ban"});if err!=nil{t.Fatal(err)};if len(p.Steps)!=1||p.Steps[0].ComponentID!="fail2ban"{t.Fatalf("plan=%#v",p)}}
''')
write('internal/helper/installer_fail2ban_linux.go',r'''//go:build linux
package helper
import("bufio";"context";"errors";"os";"os/exec";"path/filepath";"strconv";"strings")
const fail2banConfigDir="/etc/fail2ban"
const fail2banJailDir="/etc/fail2ban/jail.d"
const fail2banJailPath="/etc/fail2ban/jail.d/hyzorax-sshd.local"
const fail2banMarker="/var/lib/hyzorax-control/installer-managed/fail2ban"
const fail2banJail="[sshd]\nenabled = true\nbackend = systemd\nmode = normal\nport = ssh\nfilter = sshd\nmaxretry = 5\nfindtime = 10m\nbantime = 1h\nbanaction = nftables-multiport\n"
var fail2banPackages=[]string{"fail2ban","python3-systemd","nftables"}
func installerFail2banPreflight(ctx context.Context)(map[string]any,*Error){if os.Geteuid()!=0{return nil,&Error{Code:"installer_privilege_required",Message:"Fail2ban installer must run in the privileged helper"}};id,v,err:=fail2banOSRelease();if err!=nil||id!="ubuntu"||v!="24.04"{return nil,&Error{Code:"unsupported_os",Message:"Fail2ban installer supports Ubuntu 24.04 only"}};if _,err:=os.Stat("/usr/sbin/sshd");err!=nil{return nil,&Error{Code:"dependency_missing",Message:"OpenSSH server must already be installed before enabling Fail2ban SSH protection"}};if fail2banStateExists(ctx){return nil,&Error{Code:"component_exists",Message:"Fail2ban is already installed or configured; HYZoraX will not overwrite or adopt it"}};return map[string]any{"component":"fail2ban","ready":true,"jail":"sshd","backend":"systemd","maxretry":5,"findtime":600,"bantime":3600,"openssh_modified":false},nil}
func installerFail2banInstall(ctx context.Context)(map[string]any,*Error){if _,e:=installerFail2banPreflight(ctx);e!=nil{return nil,e};if err:=fail2banAptUpdate(ctx);err!=nil{return nil,&Error{Code:"apt_update_failed",Message:"Ubuntu package index update failed before Fail2ban installation"}};if err:=os.MkdirAll(filepath.Dir(fail2banMarker),0750);err!=nil{return nil,&Error{Code:"state_write_failed",Message:"Fail2ban ownership marker directory could not be prepared"}};if err:=os.WriteFile(fail2banMarker,[]byte("hyzorax-fail2ban-sshd\n"),0600);err!=nil{return nil,&Error{Code:"state_write_failed",Message:"Fail2ban ownership marker could not be written"}};if err:=fail2banAptInstall(ctx);err!=nil{_,_=installerFail2banRollback(ctx);return nil,&Error{Code:"package_install_failed",Message:"Fail2ban package installation failed"}};if err:=os.MkdirAll(fail2banJailDir,0755);err!=nil{_,_=installerFail2banRollback(ctx);return nil,&Error{Code:"config_directory_failed",Message:"Fail2ban jail directory could not be prepared"}};if err:=os.WriteFile(fail2banJailPath,[]byte(fail2banJail),0644);err!=nil{_,_=installerFail2banRollback(ctx);return nil,&Error{Code:"config_write_failed",Message:"HYZoraX SSH jail could not be written"}};test:=exec.CommandContext(ctx,"/usr/bin/fail2ban-client","-t");if out,err:=test.CombinedOutput();err!=nil{_,_=installerFail2banRollback(ctx);return nil,&Error{Code:"config_validation_failed",Message:"Fail2ban configuration validation failed: "+strings.TrimSpace(string(out))}};if err:=fail2banSystemctl(ctx,"enable");err!=nil{_,_=installerFail2banRollback(ctx);return nil,&Error{Code:"service_enable_failed",Message:"Fail2ban service could not be enabled"}};if err:=fail2banSystemctl(ctx,"restart");err!=nil{_,_=installerFail2banRollback(ctx);return nil,&Error{Code:"service_start_failed",Message:"Fail2ban service could not be started"}};h,e:=installerFail2banHealth(ctx);if e!=nil{_,_=installerFail2banRollback(ctx);return nil,e};h["installed"]=true;return h,nil}
func installerFail2banHealth(ctx context.Context)(map[string]any,*Error){if err:=fail2banSystemctl(ctx,"is-active");err!=nil{return nil,&Error{Code:"service_unhealthy",Message:"Fail2ban service is not active"}};test:=exec.CommandContext(ctx,"/usr/bin/fail2ban-client","-t");if out,err:=test.CombinedOutput();err!=nil{return nil,&Error{Code:"config_validation_failed",Message:"Fail2ban configuration test failed: "+strings.TrimSpace(string(out))}};status:=exec.CommandContext(ctx,"/usr/bin/fail2ban-client","status","sshd");out,err:=status.CombinedOutput();if err!=nil||!strings.Contains(string(out),"Jail: sshd"){return nil,&Error{Code:"sshd_jail_unhealthy",Message:"Fail2ban sshd jail is not active"}};max,err:=fail2banGetInt(ctx,"maxretry");if err!=nil||max!=5{return nil,&Error{Code:"jail_policy_failed",Message:"Fail2ban sshd maxretry is not 5"}};find,err:=fail2banGetInt(ctx,"findtime");if err!=nil||find!=600{return nil,&Error{Code:"jail_policy_failed",Message:"Fail2ban sshd findtime is not 600 seconds"}};ban,err:=fail2banGetInt(ctx,"bantime");if err!=nil||ban!=3600{return nil,&Error{Code:"jail_policy_failed",Message:"Fail2ban sshd bantime is not 3600 seconds"}};content,err:=os.ReadFile(fail2banJailPath);if err!=nil||string(content)!=fail2banJail{return nil,&Error{Code:"managed_config_changed",Message:"HYZoraX Fail2ban sshd jail file is missing or changed"}};return map[string]any{"component":"fail2ban","active":true,"jail":"sshd","backend":"systemd","maxretry":5,"findtime":600,"bantime":3600,"openssh_modified":false},nil}
func installerFail2banRollback(ctx context.Context)(map[string]any,*Error){if _,err:=os.Stat(fail2banMarker);err!=nil{if errors.Is(err,os.ErrNotExist)&&!fail2banStateExists(ctx){return map[string]any{"component":"fail2ban","rolled_back":true,"already_absent":true},nil};if errors.Is(err,os.ErrNotExist){return nil,&Error{Code:"rollback_not_owned",Message:"Fail2ban state exists without a HYZoraX ownership marker; rollback was refused"}};return nil,&Error{Code:"rollback_state_failed",Message:"Fail2ban ownership marker could not be inspected"}};if content,err:=os.ReadFile(fail2banJailPath);err==nil&&string(content)!=fail2banJail{return nil,&Error{Code:"rollback_conflict",Message:"HYZoraX Fail2ban jail was modified; destructive rollback was refused"}};_ = fail2banSystemctl(ctx,"stop");_ = fail2banSystemctl(ctx,"disable");if err:=fail2banAptPurge(ctx);err!=nil{return nil,&Error{Code:"rollback_package_failed",Message:"Fail2ban packages could not be removed during rollback"}};_ = os.RemoveAll(fail2banConfigDir);_ = os.Remove(fail2banMarker);return map[string]any{"component":"fail2ban","rolled_back":true,"openssh_untouched":true},nil}
func fail2banGetInt(ctx context.Context,key string)(int,error){c:=exec.CommandContext(ctx,"/usr/bin/fail2ban-client","get","sshd",key);out,err:=c.CombinedOutput();if err!=nil{return 0,err};return strconv.Atoi(strings.TrimSpace(string(out)))}
func fail2banStateExists(ctx context.Context)bool{if _,err:=os.Stat(fail2banConfigDir);err==nil{return true};if _,err:=os.Stat("/usr/bin/fail2ban-client");err==nil{return true};c:=exec.CommandContext(ctx,"/usr/bin/dpkg-query","-W","-f=${Status}","fail2ban");out,err:=c.CombinedOutput();return err==nil&&strings.TrimSpace(string(out))=="install ok installed"}
func fail2banAptUpdate(ctx context.Context)error{c:=exec.CommandContext(ctx,"/usr/bin/apt-get","-o","DPkg::Lock::Timeout=120","-o","Acquire::Retries=3","update");_,err:=c.CombinedOutput();return err}
func fail2banAptInstall(ctx context.Context)error{args:=[]string{"-o","DPkg::Lock::Timeout=120","-y","--no-install-recommends","install"};args=append(args,fail2banPackages...);c:=exec.CommandContext(ctx,"/usr/bin/apt-get",args...);c.Env=append(os.Environ(),"DEBIAN_FRONTEND=noninteractive","NEEDRESTART_MODE=l");_,err:=c.CombinedOutput();return err}
func fail2banAptPurge(ctx context.Context)error{args:=[]string{"-o","DPkg::Lock::Timeout=120","-y","purge"};args=append(args,fail2banPackages...);c:=exec.CommandContext(ctx,"/usr/bin/apt-get",args...);c.Env=append(os.Environ(),"DEBIAN_FRONTEND=noninteractive","NEEDRESTART_MODE=l");_,err:=c.CombinedOutput();return err}
func fail2banSystemctl(ctx context.Context,a string)error{var args []string;switch a{case"enable":args=[]string{"enable","fail2ban"};case"restart":args=[]string{"restart","fail2ban"};case"is-active":args=[]string{"is-active","--quiet","fail2ban"};case"stop":args=[]string{"stop","fail2ban"};case"disable":args=[]string{"disable","fail2ban"};default:return errors.New("unsupported Fail2ban service action")};c:=exec.CommandContext(ctx,"/usr/bin/systemctl",args...);_,err:=c.CombinedOutput();return err}
func fail2banOSRelease()(string,string,error){f,err:=os.Open("/etc/os-release");if err!=nil{return "","",err};defer f.Close();v:=map[string]string{};s:=bufio.NewScanner(f);for s.Scan(){line:=strings.TrimSpace(s.Text());if line==""||strings.HasPrefix(line,"#"){continue};p:=strings.SplitN(line,"=",2);if len(p)==2{v[p[0]]=strings.Trim(p[1],"\"")}};if err:=s.Err();err!=nil{return "","",err};return v["ID"],v["VERSION_ID"],nil}
''')
write('internal/helper/installer_fail2ban_acceptance_test.go',r'''//go:build integration && linux
package helper
import("context";"os";"testing";"time")
func TestFail2banInstallerAcceptance(t *testing.T){if os.Getenv("HYZORAX_INSTALLER_ACCEPTANCE")!="1"{t.Skip("opt-in")};if os.Geteuid()!=0{t.Fatal("root required")};ctx,cancel:=context.WithTimeout(context.Background(),10*time.Minute);defer cancel();s:=&Server{};call:=func(a string)Response{return s.dispatch(ctx,Request{Version:ProtocolVersion,ID:a,CorrelationID:"v167",ActorID:"github-actions",Action:a,Target:"fail2ban"})};defer func(){_=call("installer.fail2ban.rollback")}();p:=call("installer.fail2ban.preflight");if !p.OK||p.Error!=nil{t.Fatalf("preflight=%+v",p)};i:=call("installer.fail2ban.install");if !i.OK||i.Error!=nil{t.Fatalf("install=%+v",i)};h:=call("installer.fail2ban.health");if !h.OK||h.Error!=nil||h.Data["jail"]!="sshd"{t.Fatalf("health=%+v",h)};r:=call("installer.fail2ban.rollback");if !r.OK||r.Error!=nil{t.Fatalf("rollback=%+v",r)}}
func TestFail2banRejectsExistingState(t *testing.T){if os.Getenv("HYZORAX_INSTALLER_ACCEPTANCE")!="1"{t.Skip("opt-in")};if os.Geteuid()!=0{t.Fatal("root required")};ctx,cancel:=context.WithTimeout(context.Background(),30*time.Second);defer cancel();if !fail2banStateExists(ctx){t.Skip("no existing state")};s:=&Server{};r:=s.dispatch(ctx,Request{Version:ProtocolVersion,ID:"existing",CorrelationID:"v167-existing",ActorID:"github-actions",Action:"installer.fail2ban.preflight",Target:"fail2ban"});if r.OK||r.Error==nil{t.Fatalf("existing state accepted: %+v",r)}}
''')
rep('internal/helper/protocol.go','const ProtocolVersion = 16','const ProtocolVersion = 17','protocol')
sp='internal/helper/server_linux.go';s=read(sp)
if 'strings.HasPrefix(request.Action, "installer.composer.") {' in s:s=s.replace('strings.HasPrefix(request.Action, "installer.composer.") {','strings.HasPrefix(request.Action, "installer.composer.") || strings.HasPrefix(request.Action, "installer.fail2ban.") {',1)
elif 'strings.HasPrefix(request.Action, "installer.fail2ban.")' not in s:raise SystemExit('timeout marker not found')
marker='''\tdefault:\n\t\tresponse.Error = &Error{Code: "action_denied", Message: "action is not allow-listed"}\n\t\treturn response\n\t}\n}'''
if marker not in s:raise SystemExit('dispatch marker not found')
cases='''\tcase "installer.fail2ban.preflight":\n\t\tif request.Target!="fail2ban"||len(request.Params)!=0{response.Error=&Error{Code:"invalid_request",Message:"Fail2ban installer request must not contain arbitrary parameters"};return response}\n\t\tdata,e:=installerFail2banPreflight(ctx);if e!=nil{response.Error=e;return response};response.OK=true;response.Data=data;return response\n\tcase "installer.fail2ban.install":\n\t\tif request.Target!="fail2ban"||len(request.Params)!=0{response.Error=&Error{Code:"invalid_request",Message:"Fail2ban installer request must not contain arbitrary parameters"};return response}\n\t\tdata,e:=installerFail2banInstall(ctx);if e!=nil{response.Error=e;return response};response.OK=true;response.Data=data;return response\n\tcase "installer.fail2ban.health":\n\t\tif request.Target!="fail2ban"||len(request.Params)!=0{response.Error=&Error{Code:"invalid_request",Message:"Fail2ban health request must not contain arbitrary parameters"};return response}\n\t\tdata,e:=installerFail2banHealth(ctx);if e!=nil{response.Error=e;return response};response.OK=true;response.Data=data;return response\n\tcase "installer.fail2ban.rollback":\n\t\tif request.Target!="fail2ban"||len(request.Params)!=0{response.Error=&Error{Code:"invalid_request",Message:"Fail2ban rollback request must not contain arbitrary parameters"};return response}\n\t\tdata,e:=installerFail2banRollback(ctx);if e!=nil{response.Error=e;return response};response.OK=true;response.Data=data;return response\n'''
s=s.replace(marker,cases+marker,1);write(sp,s)
pp='internal/helper/policy_test.go';write(pp,read(pp)+r'''
func TestInstallerFail2banRejectsParametersAndWrongTarget(t *testing.T){s:=&Server{};b:=Request{Version:ProtocolVersion,ID:"id",CorrelationID:"c",ActorID:"a",Action:"installer.fail2ban.preflight"};w:=b;w.Target="other";r:=s.dispatch(context.Background(),w);if r.OK||r.Error==nil||r.Error.Code!="invalid_request"{t.Fatalf("wrong target=%+v",r)};p:=b;p.Target="fail2ban";p.Params=[]byte(`{"jail":"custom"}`);r=s.dispatch(context.Background(),p);if r.OK||r.Error==nil||r.Error.Code!="invalid_request"{t.Fatalf("params=%+v",r)}}
''')
rep('internal/web/static/index.html','Version 1.6.6','Version 1.6.7','UI',True);rep('internal/web/assets_test.go','1.6.6','1.6.7','assets',True);rep('internal/httpapi/app_test.go','Version 1.6.6','Version 1.6.7','HTTP',True)
print('Applied HYZoraX Control Panel V1.6.7 Fail2ban SSH installer acceptance')
